import { ThemeMode } from "../types";

export const THEME_KEY = "rt_theme";

export const useColors = (theme: ThemeMode, canSubmit: boolean) => {
    const ACCENT = "#00b6ff";
    if (theme === "light") {
        return {
            screenBg: "#ffffff",
            headerBg: "#ffffff",
            headerBorder: "#dbe7f2",
            sectionBg: "#ffffff",
            sectionAlt: "#f8fbfe",
            cardBorder: "#dfe8f2",
            cardBg:"#ffffff",
            divider: "#e6edf5",
            textPrimary: "#0f172a",
            textSecondary: "#4b5a68",
            icon: "#7f93a8",
            inputBg: "#ffffff",
            inputBorder: "#d7e3ee",
            placeholder: "#96a4b2",
            chipOnBg: ACCENT,
            chipOnText: "#ffffff",
            chipOffBg: "#eef3f7",
            chipOffText: "#0f172a",
            rowBg: "#ffffff",
            rowSelected: "#e6f4ff",
            rowBorder: "#c9d9e7",
            accent: ACCENT,
            onAccent: "#ffffff",
            rightColBg: "#f3f8fc",
            rightColBorder: "#cfe0ee",
            keyPanelBg: "#f3f8fc",
            keyDisplayBg: "#ffffff",
            keyDisplayBorder: "#cfe0ee",
            keyDefault: "#ffffff",
            keyMuted: "#eef3f7",
            keyFgDefault: "#0f172a",
            keyFgMuted: "#4b5a68",
            keyBorder: "#d9e6f2",
            receiptLine: "#cfe0ee",
            receiptLineBold: "#b7cfe3",
            btnPrimary: canSubmit ? ACCENT : "#cfd9e3",
            btnPrimaryFg: "#ffffff",
            btnNeutral: "#ffffff",
            btnNeutralFg: "#0f172a",
            btnDisabled: "#cfd9e3",
            brandText: "#0f172a",
        } as const;
    }
    return {
        screenBg: "#0a0f14",
        headerBg: "#0a0f14",
        headerBorder: "#1f2a37",
        sectionBg: "#0a0f14",
        sectionAlt: "#101821",
        cardBorder: "#1f2a37",
        cardBg:"#0a0f14",
        divider: "#1f2a37",
        textPrimary: "#ffffff",
        textSecondary: "#9fb2c6",
        icon: "#9fb2c6",
        inputBg: "#101821",
        inputBorder: "#1f2a37",
        placeholder: "#7f93a8",
        chipOnBg: "#00b6ff",
        chipOnText: "#001018",
        chipOffBg: "#1b2836",
        chipOffText: "#dbeafe",
        rowBg: "#111827",
        rowSelected: "#0f1b2e",
        rowBorder: "#2a3a49",
        accent: "#00b6ff",
        onAccent: "#001018",
        keyPanelBg: "#0e1620",
        keyDisplayBg: "#0b1220",
        keyDisplayBorder: "#1f2a37",
        keyDefault: "#1f2a37",
        keyMuted: "#0e1620",
        keyFgDefault: "#dbeafe",
        keyFgMuted: "#9fb2c6",
        keyBorder: "#1a2a36",
        receiptLine: "#223140",
        receiptLineBold: "#2b3f51",
        btnPrimary: canSubmit ? "#00b6ff" : "#516273",
        btnPrimaryFg: "#001018",
        btnNeutral: "#111827",
        btnNeutralFg: "#e5e7eb",
        btnDisabled: "#516273",
        brandText: "#ffffff",
    } as const;
};
